### PR TITLE
Test and document local stress constraints with Percival

### PR DESCRIPTION
**Pull request by mohamed82008**
### Summary

A short summary of the changes in this PR.

**Highlights**:
1. In this PR, I test and document local stress constrained volume minimization problems using the augmented Lagrangian implementation in `PercivalAlg` in `Nonconvex.jl`.

### What type of change is this?

- [ ] Bug fix in a **backwards-compatible** manner.
- [ ] New feature in a **backwards-compatible** manner.
- [ ] Breaking change: bug fix or new feature that involve incompatible API changes.
- [x] Other (e.g. doc update, configuration, etc)

### Checklist

- [ ] I ran all tests on my computer and it's all green (i.e. `] test`).
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by yijiangh** [comment]
LGTM!

**Review by yijiangh — APPROVED** [review]

**Comment by yijiangh** [comment]
@mohamed82008 Is there a good paper to cite on this local stress formulation?

**Comment by mohamed82008** [comment]
>Is there a good paper to cite on this local stress formulation?

The first paper that used augmented Lagrangian to solve stress-constrained optimisation problems was back in 2004 https://link.springer.com/article/10.1007/s00158-003-0301-z.

**Comment by mohamed82008** [comment]
No one used both global and local stress measures though. Could be a good conference paper.

**Comment by yijiangh** [comment]
> The first paper that used augmented Lagrangian to solve stress-constrained optimisation problems was back in 2004 https://link.springer.com/article/10.1007/s00158-003-0301-z.
Thanks! I will add it to the example literate page - I am trying to include citation whenever we can in our docs. Our repo can be a central hub for reproducing TopOpt research!

> No one used both global and local stress measures though. Could be a good conference paper.
Good idea! TopOpt.jl definitely makes these experiments much easier to try 😸

**Pull request merged**
